version: "3.8"

services:
  mc-server:
    build: .
    container_name: minecraft-custom
    ports:
      - "${MC_PORT}:25565"
    environment:
      EULA: "${EULA}"
      MEMORY: "${MEMORY}"
      ENABLE_COMMAND_BLOCK: "${ENABLE_COMMAND_BLOCK}"
      DIFFICULTY: "${DIFFICULTY}"
      MAX_PLAYERS: "${MAX_PLAYERS}"
    volumes:
      - mc-data:/app
    restart: on-failure

volumes:
  mc-data: